# Generated by Django 4.1 on 2022-09-26 01:41

import crud.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='desc',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=crud.models.filepath),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
